### ISSUE TITLE
[feature] Parametrize cluster add-on CNI name

### ISSUE THREAD

**Issue by seifrajhi** [shalb/cdev-aws-eks#14]
**Current Behavior:**

The current configuration hard codes the Cluster Network Infrastructure (CNI) name in the `cluster_addons` section, making it less flexible for users who wish to use a different CNI plugin.

```yaml
cluster_addons:
  coredns:
    most_recent: true
  kube-proxy:
    most_recent: true
  vpc-cni:
    most_recent: true
```

**Desired Behavior:**

Allow users to parametrize the CNI name or specify a custom CNI plugin in the `cluster_addons` section. 

In this case, I would like to be able to use a variable for the Cilium CNI, which we can set as  `{{ .variables.cni }}`, to either use `vpc-cni` or installing another CNI using `GitOps`  i.e `argoCD` 

Therefore, like in the module `aws-ia/eks-blueprints-addons/aws` which gives possibility to  install CNI cilium as a `helm release`
